# Generated by Django 5.2.1 on 2025-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('recipe', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=100)),
                ('flavor_profiles', models.JSONField(default=list, help_text='A list containing the flavor profiler og the meal')),
            ],
        ),
    ]
